### ISSUE TITLE
Missing docs for cloudctxprofile data source

### ISSUE THREAD

**Issue by nfagerlund** [terraform-providers/terraform-provider-aci#1]
Hello! There's a broken link in the sidebar pointing to `d/cloudctxprofile.html`, currently breaking builds for hashicorp/terraform-website. The page for that data source doesn't exist, but it looks like an implementation does exist at `./aci/data_source_aci_cloudctxprofile.go`.

**Comment by nkatarmal-crest** [comment]
I have added the documentation for the mentioned data source. PR #4 contains the changes.

**Comment by nfagerlund** [comment]
excellent, thanks!
