### ISSUE TITLE
Rename aci_switch_association to aci_leaf_selector

### ISSUE THREAD

**Issue by vfiftyfive** [terraform-providers/terraform-provider-aci#109]
Rename resource `aci_switch_association` to `aci_leaf_selector`.

Nic

**Comment by Atul9** [comment]
Hi @vfiftyfive I would like to take this up

**Comment by vfiftyfive** [comment]
Please feel free to submit a PR!
Thanks

Nic

**Comment by Atul9** [comment]
@vfiftyfive done, I have opend up a PR at https://github.com/terraform-providers/terraform-provider-aci/pull/114
