### ISSUE TITLE
aci_logical_node_profile relations attributes 

### ISSUE THREAD

**Issue by JBaptisme33** [terraform-providers/terraform-provider-aci#21]
Hello team,

Thanks for your hard work.

We are facing issue regarding applicable attributes to an L3Out Node profile.
Indeed, relation_l3ext_rs_node_l3_out_att argument seem have missing parameters.
When adding a node to a profil, two parameters are mandatory:
- Node ID 
- Router ID

Node ID (tDn) can be sent, but Router ID (rtrId) can't be sent to APIC.
Is there a way to add a node to L3Out Profile ? 

For example code below does not work, seem mandatory **rtrId** param is not available and therefore sent to APIC.

`resource "aci_logical_node_profile" "test-1" {
        l3_outside_dn = "${aci_l3_outside.interco_TEST.id}"
        name          = "interco_OSPF_testt-1"
        relation_l3ext_rs_node_l3_out_att = ["topology/pod-1/node-101"]
}`

Thans for help !

**Comment by nkatarmal-crest** [comment]
We need to expose this relation class as concrete resource in the provider.

**Comment by nkatarmal-crest** [comment]
@JBaptisme33 I have exposed the class as concrete resource in the provider version 0.2.1. Please find the below document for your reference. https://www.terraform.io/docs/providers/aci/r/l3extrsnodel3outatt.html

**Comment by JBaptisme33** [comment]
Hello @nkatarmal-crest . Thanks for effort.
I will try as soon as possible.

Really thanks,
