### ISSUE TITLE
Rate limiting issues still present in 0.2.0

### ISSUE THREAD

**Issue by kecorbin** [terraform-providers/terraform-provider-aci#30]
The 0.2.0 version of the provider does seemed to have improved on the rate limiting issues when using user/pass auth, however, I am still hitting it from time to time, far less frequent than in previous versions though. The error I receive is on random resources like below

```
Error: invalid character '<' looking for beginning of value

  on vlan/logical.tf line 1, in resource "aci_tenant" "tenant":
   1: resource "aci_tenant" "tenant" {

Error: invalid character '<' looking for beginning of value

  on vlan/logical.tf line 1, in resource "aci_tenant" "tenant":
   1: resource "aci_tenant" "tenant" {

Error: invalid character '<' looking for beginning of value

  on vlan/logical.tf line 1, in resource "aci_tenant" "tenant":
   1: resource "aci_tenant" "tenant" {
```

Given enough attempts at a plan, it will ultimately work.

**Comment by nkatarmal-crest** [comment]
@kecorbin It would be good if you can share the .tf files you are using to create the resources. I can debug the issue properly from my side and get back to you with a concrete solution for the same. Meanwhile if you don't want to waste your time in running the Terraform plan multiple times, i will suggest you to use --parallelism=1 flag to avoid the issue till we have the proper fix in place.

**Comment by kecorbin** [comment]
@nkatarmal-crest https://gitlab.com/kecorbin/terraform-aci-network-centric/-/tree/master

**Comment by nkatarmal-crest** [comment]
@kecorbin Can you give a try to version 0.2.1 of the provider?

**Comment by kecorbin** [comment]
I still saw issues w/ 0.2.1 when using user/pass auth.  With #28 now closed, I'm able to use cert based auth

**Comment by nkatarmal-crest** [comment]
Can you export TF_LOG_FILE = logs.txt and with TF_LOG = TRACE. I want to double check the authentication endpoint.

**Comment by nkatarmal-crest** [comment]
Closing this issue as we haven't heard anything back from the reporter.
