### ISSUE TITLE
preferred group object aci_any

### ISSUE THREAD

**Issue by Bullenj01** [terraform-providers/terraform-provider-aci#31]
In the documentation there is a aci_any resource but when used terraform says the provider does not support it.  Looking in the master branch I see a vzany resource but not an aci_any.  I tried vzany but it was not recognized either.  I'm using the latest .2 code.

**Comment by nkatarmal-crest** [comment]
@Bullenj01 can you pull the version 0.2.1 and check if the resource you are looking for is available or not?

**Comment by Bullenj01** [comment]
Confirmed resolved in 0.2.1
