### ISSUE TITLE
aci_rest is not working when using signature-based authentication with error-message "Bad Signature"

### ISSUE THREAD

**Issue by twtko** [terraform-providers/terraform-provider-aci#34]
I found that aci_rest does not work when using signature-based authentication for APIC.

APIC: 4.2(3n)
Terraform: 0.12.24
provider: 0.2.1

When I use signature-based authentication for APIC.

```
(snip)
Terraform will perform the following actions:

  # aci_rest.l3out_domain will be created
  + resource "aci_rest" "l3out_domain" {
      + class_name = "l3extRsL3DomAtt"
      + content    = {
          + "tDn" = "uni/l3dom-L3-out-Domain"
        }
      + dn         = (known after apply)
      + id         = (known after apply)
      + path       = "api/node/mo/uni/tn-Tenant10/out-L3out_OSPF/rsl3DomAtt.json"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aci_rest.l3out_domain: Creating...

Error: bad signature

  on lab03.tf line 19, in resource "aci_rest" "l3out_domain":
  19: resource "aci_rest" "l3out_domain" {
```

When I use password-based authentication for APIC.

```
(snip)
Terraform will perform the following actions:

  # aci_rest.l3out_domain will be created
  + resource "aci_rest" "l3out_domain" {
      + class_name = "l3extRsL3DomAtt"
      + content    = {
          + "tDn" = "uni/l3dom-L3-out-Domain"
        }
      + dn         = (known after apply)
      + id         = (known after apply)
      + path       = "api/node/mo/uni/tn-Tenant10/out-L3out_OSPF/rsl3DomAtt.json"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aci_rest.l3out_domain: Creating...
aci_rest.l3out_domain: Creation complete after 1s [id=uni/tn-Tenant10/out-L3out_OSPF/rsl3DomAtt]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by nkatarmal-crest** [comment]
@twtko It's the issue with wrong terraform configuration. See the value of path field in the .tf file.

```
path       = "api/node/mo/uni/tn-Tenant10/out-L3out_OSPF/rsl3DomAtt.json"
```

There should be a `/` before api. It will work fine with it.

**Comment by twtko** [comment]
@nkatarmal-crest I have tried this again with added `/`, However the result was not success with below error message.

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aci_rest.l3out_domain: Creating...
aci_tenant.target_tenant: Creating...
aci_tenant.target_tenant: Creation complete after 1s [id=uni/tn-Tenant10]
aci_l3_outside.l3out_ospf: Creating...
aci_vrf.target_vrf: Creating...
aci_l3_outside.l3out_ospf: Creation complete after 1s [id=uni/tn-Tenant10/out-L3out_OSPF]
aci_vrf.target_vrf: Creation complete after 1s [id=uni/tn-Tenant10/ctx-VRF1]

Error: configured object ((Dn0)) not found Dn0=uni/tn-Tenant10/out-L3out_OSPF/rsl3DomAtt, 

  on lab03.tf line 19, in resource "aci_rest" "l3out_domain":
  19: resource "aci_rest" "l3out_domain" {
```

There is no  `/` on "path" parameter at Official document on terraform.io.
https://www.terraform.io/docs/providers/aci/r/rest.html

I believe we should be use it without `/` on top of "path" parameter.
My resource config as below.

```
resource "aci_rest" "l3out_domain" {
  path = "api/node/mo/uni/tn-${var.aci_tenant_name}${var.aci_pod_id}/out-${var.aci_l3out_name}/rsl3DomAtt.json"
  class_name = "l3extRsL3DomAtt"

  content = {
    "tDn" = "uni/l3dom-L3-out-Domain"
  }
}
```

**Comment by nkatarmal-crest** [comment]
@twtko the error is not related to `/`. We will need to add the `/` before the api word in the path, there is a miss in the documentation i will update it. 


The error you are facing is because terraform is trying to create the aci_rest resource before even creating the Tenant, if you check the execution plan you will get that the aci_rest was executed before the aci_tenant. So APIC was not able to fine the tenant we passed in the aci_rest resource. For that you will need to add the explicit dependancies using the depends_on operator of terraform. Please find the more information on the depends_on as below,

https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies

**Comment by twtko** [comment]
@nkatarmal-crest Thank you very much giving me your explanation. I understand why I need to add `/`, but I couldn't understand why the behavior is different in case of using password-based authentication and certificate-based authentication.
