### ISSUE TITLE
Add Feature: Create contract subjects, filters and filter entries inline in contract resource

### ISSUE THREAD

**Issue by vfiftyfive** [terraform-providers/terraform-provider-aci#38]
In the current provider version, the only way to create a complete contract is to create the distinct resources composing it and interpolate them where required.
The proposed featured consists in providing a block within the contract resource that defines all required components. This includes subject, filters and filter entries.

Nic

**Comment by nkatarmal-crest** [comment]
@vfiftyfive we have added this feature.

Doc: https://www.terraform.io/docs/providers/aci/r/vzbrcp.html

Can we close this isssue?
