### ISSUE TITLE
Filter Entry resource flagged for modification when common protocol is used

### ISSUE THREAD

**Issue by vfiftyfive** [terraform-providers/terraform-provider-aci#39]
Consider the following resource:
```
resource "aci_filter_entry" "filter_entry" {
  filter_dn   = aci_filter._.id
  name        = var.filter_name
  d_from_port = "443"
  d_to_port   = "443"
  ether_t     = "ip"
  prot        = tcp
}
```

APIC will re-write "443" as "HTTPS". This will lead to drift of state between the infrastructure and the state file. As a consequence, the next time the plan is executed, the resource will be flagged as requiring modification. This is because Terraform needs to reconcile the state file with the value back to "443".

Nic

**Comment by nkatarmal-crest** [comment]
@vfiftyfive We have fixed this issue in the latest version of provider v0.3.0. Let me know if you are still facing this issue.
