### ISSUE TITLE
Issue re-applying terraform

### ISSUE THREAD

**Issue by francesco-supportlan** [terraform-providers/terraform-provider-aci#44]
Hi
Did you changed the way the resources are created modified?

I have this example sample:

resource "aci_vlan_pool" "test_vlan_pool" {
  name  = "TEST_VLAN_POOL"
  alloc_mode  = "static"
}
resource "aci_ranges" "vlanpool1" {
  depends_on = [
    aci_vlan_pool.test_vlan_pool,
  ]
  vlan_pool_dn  = aci_vlan_pool.test_vlan_pool.id
  _from  = "vlan-100"
  to  = "vlan-100"
  from  = "vlan-100"
  alloc_mode  = "static"
}

Once it's applied, if I do re-apply, nothing was going to happen as expected. But since version 0.2.3, it destroy and recreate the resource which can brings some issues while doing in production.

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aci_ranges.vlanpool1 must be replaced
-/+ resource "aci_ranges" "vlanpool1" {
        _from        = "vlan-100"
        alloc_mode   = "static"
      + annotation   = (known after apply)
      + description  = (known after apply)
        from         = "vlan-100"
      ~ id           = "uni/infra/vlanns-[TEST_VLAN_POOL]-static/from-[vlan-100]-to-[vlan-100]" -> (known after apply)
      + name_alias   = (known after apply)
      ~ role         = "external" -> (known after apply)
        to           = "vlan-100"
      ~ vlan_pool_dn = "uni/infra" -> "uni/infra/vlanns-[TEST_VLAN_POOL]-static" # forces replacement
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aci_ranges.vlanpool1: Destroying... [id=uni/infra/vlanns-[TEST_VLAN_POOL]-static/from-[vlan-100]-to-[vlan-100]]
aci_ranges.vlanpool1: Destruction complete after 0s
aci_ranges.vlanpool1: Creating...
aci_ranges.vlanpool1: Creation complete after 0s [id=uni/infra/vlanns-[TEST_VLAN_POOL]-static/from-[vlan-100]-to-[vlan-100]]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

**Comment by nkatarmal-crest** [comment]
@francesco-supportlan I am working on this issue, it seems it's not able to read the parentDN in this case.

**Comment by nkatarmal-crest** [comment]
@francesco-supportlan Please use the latest version of provider v0.3.0. In which we have fixed this issue. Let me know if your are still seeing this.
