### ISSUE TITLE
Add feature: specify port-group security options in VMM domain binding

### ISSUE THREAD

**Issue by cpaggen** [terraform-providers/terraform-provider-aci#49]
In resource **aci_application_epg**, it is possible to bind domain _"aci_vmm_domain.vds"_ to the EPG like so:

- relation_fv_rs_dom_att = [data.aci_vmm_domain.vds.id]

However, it isn't possible to specify many common domain binding options such as resolution immediacy, deployment immediacy, VMM port-group security settings, etc. In other words, attributes:

- resImedcy
- instrImedcy

and child vmmSecP's attributes 

- allowPromiscuous
- forgedTransmits
- macChanges

should be user-configurable. Doing this inside the **aci_application_epg** resource is probably not very practical nor elegant, it is likely a new resource to bind domains to EPGs will be required. That resource shall refer to the EPG it's binding a domain to.

**Comment by nkatarmal-crest** [comment]
@cpaggen Thanks for bringing this to our attention. We will add a separate resource for the same.

**Comment by nkatarmal-crest** [comment]
@cpaggen We have added new resource to address this request.
Please find the doc link here: https://www.terraform.io/docs/providers/aci/r/fvrsdomatt.html
