### ISSUE TITLE
VPC Logical Pair Id seem missing in resource_aci_fabricexplicitgep.go

### ISSUE THREAD

**Issue by JBaptisme33** [terraform-providers/terraform-provider-aci#72]
Hello,

Again, thanks for your big work, it improve our daily work a lot 
Logical Pair Id paramater seem missing in aci_vpc_explicit_protection_group

Indeed, after creating a protection group, there is a issue regarding actual Logical Pair Id (0) instead of number between 1 to 1000

Logical Pair Id seem available in same class then others parameters (fabric:ExplicitGEp / fabric:AProtGEp:id) https://pubhub.devnetcloud.com/media/apic-mim-ref-301/docs/MO-fabricExplicitGEp.html 

Is it possible to implement it in next release ?

thanks again,

**Comment by nkatarmal-crest** [comment]
@JBaptisme33  https://www.terraform.io/docs/providers/aci/r/fabricexplicitgep.html#vpc_explicit_protection_group_id, here is the attribute you are looking for. Let me know if you need any help with that.

**Comment by JBaptisme33** [comment]
Hi
I'm a bit confused.
I will try tomorrow again but vpc_explicit_protection_group_id require a string and I want to give a number between 1 and 10000.
I was able to fix the value via the rest modulebut I don't understand via this terraform ressource how link is done between this attribute and the final explicit value for the vpc domain 

Thanks again 

Jean-Baptiste

**Comment by nkatarmal-crest** [comment]
@JBaptisme33 though it's a string it will convert your number internally and will pass it to the payload. vpc_explicit_protection_group_id attribute is mapped to the id in the JSON payload.

**Comment by JBaptisme33** [comment]
Hello,
I've understood.
Id need to be passed as number, anad not a string like
`vpc_explicit_protection_group_id = 3`
and not   
`vpc_explicit_protection_group_id = "3"
`
It is ok right now,
