### ISSUE TITLE
EPG Subnet

### ISSUE THREAD

**Issue by maty0609** [terraform-providers/terraform-provider-aci#80]
I'm not sure if I have missed something but I would need to add EPG Subnet. Is this supported?

I can't see anything here https://www.terraform.io/docs/providers/aci/r/fvaepg.html

Thank you!

**Comment by aj-cruz** [comment]
@maty0609 Try this: [https://www.terraform.io/docs/providers/aci/d/fvsubnet.html](url)

**Comment by nkatarmal-crest** [comment]
@maty0609 We have a separate resource to manage the subnets. You can find it here https://www.terraform.io/docs/providers/aci/r/fvsubnet.html. In the parameter bridge_domain_dn if you pass the value of EPG dn, it will create the subnet under the EPG. This will unblock you on your work meanwhile i will add a concrete solution for this use-case.

**Comment by maty0609** [comment]
Brilliant. That one worked! Thank you for your help.

**Comment by vfiftyfive** [comment]
User problem solved
